import HomePage from "./HomePage";
import ErrorPage from "./ErrorPage";
import Layout from "./Layout";
import Login from "./Login";
import Register from "./Register";
import Project from "./Project";
import ChooseSub from "./ChooseSub";
import Events from "./Events";
import EventList from "./EventList";
import Community from "./Community";
import Projects from "./Projects";
import UserLayOut from "./UserLayout";
import PriceTable from "./PriceTable";
import Orders from "./Order";
import RegisterFarmer from "./RegisterFarmer";
export {HomePage, ErrorPage, UserLayOut, Layout ,Events, Login ,Register, Project, ChooseSub,EventList,PriceTable ,Community,Orders, Projects, RegisterFarmer};